### ISSUE TITLE
USERSTORY(# 1):   Gather General Requirements and visual layout

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#14]
As a developer, I can see how the site should be laid out so that the functionality can be developed incrementally

EPIC #1 

Acceptance criteria
1. Given that I am a developer, I will understand exactly what the goals of the site are.
2. Given I am a developer, I will have a clear visual plan of the front end of the website and the user journey
3. Given I am a developer I will understand the relationship between the database models

Tasks
- [x] Write general requirements doc
- [x] Create wireframes
- [x] Create database schematic
- [x] Research Bootstrap templates
- [x] Create Logo
- [x] Decide Color scheme
- [x] Choose font styles
- [x] Gather graphics, icons and images
- [x] Write content for pages

Story Points = 1

**Comment by rstan-dev** [comment]
Colors:  # fb8500 (main orange)
white text on orange
black text and headings on white background


______________

Fonts:  Roboto, sans serif

______________

Content for Pages

Small Van in Kemp Town
Size: Small
Load Area (WxHxL): 1.2m x 1.5m x 1.2m
Suitable for: General items, luggage, small boxes
Crew: 1
Location: Brighton
County: East Sussex

Small Van in Camden Town
Size: Small
Load Area (WxHxL): 1.2m x 1.5m x 1.2m
Suitable for: Small boxes, personal items
Crew: 1
Location: London
County: Greater


Medium Van in Croydon
Size: Medium
Load Area (WxHxL): 1.7m x 1.8m x 2.9m
Suitable for: Small furniture, office moves
Crew: 2
Location: London
County: Greater London

Medium Van in Stockport
Size: Medium
Load Area (WxHxL): 1.7m x 1.8m x 2.9m
Suitable for: Office furniture, large boxes
Crew: 2
Location: Manchester
County: Greater Manchester


Large Van in Sutton Coldfield
Size: Large
Load Area (WxHxL): 2.2m x 4.0m x 2.2m
Suitable for:  Furniture, 1 bedroom flat contents
Crew: 2
Location: Birmingham
County: West Midlands


Large Van in Jesmond
Size: Large
Load Area (WxHxL): 2.2m x 4.0m x 2.2m
Suitable for:  Large furniture, household appliances
Crew: 2
Location: Newcastle
County: Tyne & Wear


Large Van in Manchester
Size: Large
Load Area (WxHxL): 2.2m x 4.0m x 2.2m
Suitable for:  Large furniture, household appliances
Crew: 2
Location: Manchester
County: Greater Manchester

https://bootstrapmade.com/demo/Lumia/
https://getbootstrap.com/docs/4.2/components/buttons/

**Comment by rstan-dev** [comment]
all completed
