### ISSUE TITLE
USERSTORY(#2):   Initial Django project setup  

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#15]
As a developer, I can access the initial project files in my developer environment, and deploy to Heroku, so that I can resolve any deployment issues early on.  

EPIC #2 

Acceptance criteria
1. Given that I am a developer, I will open a Django project in GitPod using the CI template
2. Given that I am the developer I will build an agile project board with user story templates, including acceptance criteria and tasks.
3. Given the User stories and tasks are loaded onto the project board, according to epics.  Each item will be labelled according to the MoSCoW system and prioritised according to the order of incremental development
4. Given that I am a developer I will deploy a basic project to Heroku from the outset, ensuring any secret keys remain hidden

Tasks
- [x] Create GitHub Repo
- [x] Create Project Board and user story templates
- [x] Add epics and user story items to Kanban board and prioritise into sprints
- [x] Create Readme empty template
- [x] Create Django project
- [ ] Create Static Files
- [x] Create SQL Database
- [x] Create Secret Keys
- [x] Create env.py and git.ignore
- [x] Create Heroku project
- [x] Initial Early Deployment

Story Points = 2

**Comment by rstan-dev** [comment]
The initial app deployed to Heroku successfully. media static and templates folder created
