### ISSUE TITLE
USERSTORY(#3):  Create bootstrap template

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#16]
As a developer I can deploy a basic site design so that it meets the minimum viable requirements 

EPIC #3 

Acceptance criteria
Given that I am a developer, I will create basic bootstrap pages, based on the wireframes and concept art, that will form the structure of the website

Tasks
- [x] Create Base.html
- [x] Create Header
- [x] Create Footer
- [x] Create Navbar
- [x] Create Home Page
- [x] Create Services Page
- [x] Create Contact Page
- [x] Create Van Detail Page
- [x] Create Van Search Filters results Page
- [x] Create Account Login Page
- [ ] Create Forgot Password Page
- [x] Create Account Register Page
- [x] Create Create Booking Page
- [x] Create Users Dashboard Page
- [x] Create Edit Booking Page
- [x] Add favicon

Story Points = 2

**Comment by rstan-dev** [comment]
Will create forgot pw page when needed
