### ISSUE TITLE
USERSTORY(#5 ):  Create Van Model 

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#18]
As an admin user I can create Van details in the admin area so that they populate fields on the front end template

EPIC #4 

Acceptance criteria
1. Given that I am an admin, I can login to Django admin area  and create a new van listing 
2. Given that I am an admin I can publish or unpublish the van listing
3. Given that I am an admin I can edit or delete a van listing which will update the front end
4. Given that I am a front end user, I can see all the van listings appear on the front end

Tasks
- [x] Create van app
- [x] Create templates folder with van_type and display_vans pages
- [x] Create van model and database fields
- [x] Host pics on cloudinary
- [x] Migrate database
- [x] Create URL pattern
- [x] Add URL path to project URL
- [x] Register model in admin.py
- [x] Create view methods
- [x] Create / Link to template
- [x] Connect to urls.py
- [x] Update html templates
- [x] Add pagination for more than 6 vans

Story Points = 4

**Comment by rstan-dev** [comment]
Added slug field to DB.
Added price field for future enhancement

**Comment by rstan-dev** [comment]
Created van_detail page using int:slug.  
Need to update view with get_object_or_404

**Comment by rstan-dev** [comment]
Add pagination task to small items to resolve

**Comment by rstan-dev** [comment]
Added Detail slug links to index and all_vans page and tested as working.  Closing this user story
