### ISSUE TITLE
USERSTORY(#7):  Display Van detail 

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#20]
As a website user, I can read more detail about a van so I can book or enquire

EPIC #4 

Acceptance criteria
1. Given that I am a front-end user, when I click on the detail button, I will be taken to a new page specific for that van listing
2. Given that I am a front-end user, I will see van details, some feedback, a button to enquire and a button to book
3. Given that I am a front-end user, the enquire button will take me to the contact page to send a message
4. Given that I am a front-end user, the Book button will take me to the login page or to the dashboard to make a booking

Tasks

- [x] Link the detail Button to a new view
- [x] Display van data in template 
- [x] Link the Enquire button to the contact form page
- [x] Link the Book button with conditional if they are logged in or not
- [x] Display feedback

Story Points = 2

**Comment by rstan-dev** [comment]
Added Enquire Button Task to UserStory19 - #31

**Comment by rstan-dev** [comment]
Added Link Booking Button task to Small Items to resolve list - needs to be done after User Account creation, booking model, booking form, create booking and user dashboard view has been completed
