### ISSUE TITLE
USERSTORY(#10 ): User Registration        

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#23]
As a website user, I can register, log in and log out to view my dashboard

EPIC #5 

Acceptance criteria
1. Given I am a website user when I click on register it brings me to a registration form
2. Given I am a website user when I click on login, it brings me to a login form
3. Given I am a website user when I click on logout it logs me out and redirects me to the home page

Tasks
- [x] Create accounts app
- [x] Create views
- [x] Write register function
- [x] Write login function
- [x] Write logout function
- [x] Write dashboard function
- [x] Add url patterns
- [x] Link to templates

Story Points = 2

**Comment by rstan-dev** [comment]
Decided to use all auth as a more comprehensive login and user registration option

**Comment by rstan-dev** [comment]
Dashboard complete, When user logs in it redirects to dashboard.  
Needs user conditional to be applied when there is booking info - added to small items to resolve
Needs Dashboard Link in Menu Bar - added to small items to resolve
Needs Welcome { user.name } to display on screen - added to small items to resolve
