### ISSUE TITLE
USERSTORY(# 11 ):   Create Booking Model

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#24]
As an admin user, I can create Booking details in the admin area so that I can take a booking over the phone

EPIC #6 

Acceptance criteria
1. Given that I am an admin, I can log in to the Django admin area and create a new van booking
2. Given that I am an admin, I will be able to change the status of a booking from Pending to Approved to Completed 
3. Given that I am an admin after the booking date has passed, I will be able to change the Status to Completed which will also change the status on the Users Dashboard

Tasks
- [x] Create Booking app
- [x] Create Booking model and database fields
- [x] Migrate database
- [x] Register model in admin.py
- [x]  Add list_display, list_display_links, list_filter, List_editable, search_fields and list_per_page
- [x] Add some booking data to test

Story Points =

**Comment by rstan-dev** [comment]
I have decided not to create separate apps for this project, all models will be maintained in one models.py file

**Comment by rstan-dev** [comment]
Unique booking number field added based on the id number + 1000

**Comment by rstan-dev** [comment]
choices.py file created to access Size, Location and County choice in Van and Booking model

**Comment by rstan-dev** [comment]
booking_number field is working - generates a number and set to readonly
