### ISSUE TITLE
USERSTORY(#12 ):  View Bookings on User Dashboard      

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#25]
As a logged in user, I can view any bookings I have made in a list on my Dashboard

EPIC #6 

Acceptance criteria
1. Given I am a user, I will need to log in to access the dashboard
2. Given I am a user, once I have logged in I will see a list of bookings on the Dashboard
3. Given I am a user, the booking info will contain the booking date, location, van size and booking status 

Tasks
- [x] Create URL pattern
- [x] Add URL path to project URL
- [x] Create view method
- [x] Create add functionality
- [x] Create Dashboard view
- [x] Create / Link to template
- [x] Connect to urls.py
- [x] Display a list of booking data

Story Points = 2

**Comment by rstan-dev** [comment]
all completed except for "Create add functionality" which is covered under User Story 13
