### ISSUE TITLE
USERSTORY(# 13):  Create Booking on User Dashboard

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#26]
As a logged-in user I can create a booking from a listing page, which will appear on the user's dashboard

EPIC #6

Acceptance criteria
1. Given I am a user, If I am not logged in, the booking button on the van detail page will redirect me to the login page
2. Given I am a user, If I am logged in I will be directed to my dashboard where I can add a booking using the + button
3. Given I am a user, once the booking details have been submitted the booking will appear on my dashboard as pending Status
4. Given I am an admin, I will see the booking reflected on my admin dashboard
5. Given I am the user, when the admin approves the booking, the Status will change to approved and this will be reflected on my dashboard

Tasks
- [x] Link the booking button on the detail page to the booking page, or login page - using a conditional if the user is logged in or not
- [x] Create a booking form that submits relevant data to the database
- [x] Display new booking details on the User's dashboard
- [x] Create an Add Booking button on the Dashboard that links to the booking form

Story Points = 2

**Comment by rstan-dev** [comment]
To consider:

1. Customer cannot choose a Booking date  in the past (validate date)
2. Booking form and update booking form should be onscreen modals
3. User must be Logged in to make a booking - use LoginRequiredMixin. (define LOGIN_URL in settings)
4.  Consider Crispy forms (also can be used to style ligin and register page
5.
