### ISSUE TITLE
USERSTORY(#14 ): Edit Booking on User Dashboard 

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#27]
As a logged in User, I can edit the booking details from the Dashboard so I can make any changes

EPIC #6 

Acceptance criteria
1. Given I am a user, the Edit button will open up the Update Booking Page
2. Given I am a user, the update Booking Button will update the database, and the dashboard and change the status back to pending

Tasks
- [x] Create Edit Button and add to Dashboard
- [x] Link edit button to edit booking template
- [x] Use the same form as create booking but pre-populated with current booking info
- [x] Update Booking button submits changes to db and dashboard 
- [x] Status reverts to pending

Story Points = 2

**Comment by rstan-dev** [comment]
How to approach:

1. associate edit button with booking using booking.id
2. create a unique identifier for edit button on dashboard- using booking.id
3. Add a click event on button
4. Get booking.id - request booking details to populate modal
