### ISSUE TITLE
USERSTORY(#15 ):  Delete booking on user dashboard   

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#28]
As a logged in User, I can delete the booking details from the Dashboard 

EPIC #6 

Acceptance criteria
1. Given I am a user, the Delete booking button creates a popup modal message in my dashboard confirming delete or cancel
2. Given I am a user, Clicking Delete, removes all the booking info from the DB
3. Given I am a user, Clicking cancel, closes the modal and returns me to the Dashboard screen

Tasks
- [ ] Create a delete button on the Dashboard
- [ ] Create the Pop-up modal to confirm or cancel the instruction
- [ ] Configure the delete button and the delete function
- [ ] Configure the cancel modal button

Story Points = 2

**Comment by rstan-dev** [comment]
Modal not used, Delete Button directs to a separate delete_booking.html
