### ISSUE TITLE
USERSTORY(#19):  Send email to admin via contact form

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#31]
As an admin, I can receive an email with the details from the contact form, so I can follow up with the customer

EPIC #8 

Acceptance criteria
1. The details from the contact form will be sent to the registered admins' email address

Tasks
- [x] Create a form containing name, email, and message with Enquire button.
- [x] Link to Contact template
- [x] Link to Enquire button on Van Detail Page
- [x] Ensure buttons are linked correctly
- [x] Enquire button to send contents of form to admin’s email
- [x] Configure email server
- [x] Test emails are sent and received
- [x] Ensure credentials are securely stored

Story Points = 2

**Comment by rstan-dev** [comment]
Configure emails to be sent from contact form or from van_detail button,
If sent from contact form - no van details mentioned, user redirected to home page. If sent from van_detail page, user is redirected back to van-detail page.  
Updated contact view, create alternative contact url with van slug, add conditional to van_detail button.

Emails tested in dev environment as GitHub does not allow smtp sending.  
Email Config settings are: 
#Setting for development tests (remove for production)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Setting for production (enable for deployment)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
