### ISSUE TITLE
USERSTORY(#20 ):  Send booking email notifications     

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#32]
As a user I can receive an email notification when the booking has been created, approved, updated or deleted,  so I can manage the booking in my account 

EPIC #9 

Acceptance criteria
1. Given I am a user, the details from a new booking I have made will be sent to me by email
2. Given that I am a user the details from an updated booking will be sent to me via email
3. Given that I am a user the details from a deleted booking will be sent to me via email
4. Given that I am an admin, when I approve a booking, an email notification will be sent to the user
5. Given I am an admin, the details from a new booking when it has been made will be sent to me by email
6. Given that I am an admin the details from an updated booking will be sent to me via email
7. Given that I am an admin the details from a deleted booking will be sent to me via email

Tasks
- [x] Implement email functionality
- [x] Trigger an email to the user on booking
- [x] Trigger an email to the user on updating a booking
- [x] Trigger an email to the user on deleting a booking
- [x] Trigger an email to the user when the admin approves a booking
- [x] Trigger an email to the user when the admin completes the booking and feedback can be left
- [x] Trigger an email to the admin on creating a booking
- [x] Trigger an email to the admin on updating a booking
- [x] Trigger an email to the admin on deleting a booking

Story Points =  2

**Comment by rstan-dev** [comment]
Model updated to trigger emails when Booking Status changed to Approved or Completed.

If Admin deletes a booking from the admin area - the user does not get a notification as yet. Raised a sa small item / future dev
