### ISSUE TITLE
USERSTORY(#23 ):  Onscreen notification when logged in or out

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#36]
As a user, I will see a on-screen notification to let me know I have logged in or logged out

EPIC #10 

Acceptance criteria
1. Given I am a website user, I will see an onscreen notification for 3 seconds on the Dashboard when I log in
3. Given I am a website user, I will see a 3-second on-screen notification on the home page when I have logged out

Tasks
- [x] Create partial alerts.html
- [x] Implement JS setTimout() for messages
- [x] Update accounts views

Story Points = 2

**Comment by rstan-dev** [comment]
1. added onscreen messages to index page and dashboard

**Comment by rstan-dev** [comment]
Success sign out message displayed on home page on log-out
Success sign-in message on dashboard when logged in
