### ISSUE TITLE
USERSTORY(#25 ):  Create user story tests

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#38]
As a developer, all user story tests will pass, so that I can be certain the site functons as intended

EPIC #11 

Acceptance criteria
1. User Story Tests passed

Tasks
- [x] Create a Testing.md doc with tests Performed Table 
- [x] Perform Manual tests for each user story
- [x] Document failures in Readme and rectify
- [x] Document Bugs found and how fixed
- [x] Document any Bugs left unfixed

Story Points = 6

**Comment by rstan-dev** [comment]
Manual User Story tests completed in dev environment and bugs fixed.
Docs to be updated added to final US.

These tests to be repeated in production environment before closing ticket

**Comment by rstan-dev** [comment]
All tests passed in Production environment
