### ISSUE TITLE
USERSTORY(# 26):  Test Html, CSS, JS, Python, Lighthouse 

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#39]
As a developer all code will pass through validation tools to identify any issues, errors or non-conformance

EPIC #11 

Acceptance criteria
1. Pass HTML test
2. Pass CSS test
3. Pass JS test
4. Pass Python script test
5. Pass Lighthouse test

Tasks
- [x] W3 Validation - add to Readme
- [x] W3C Validation - add to Readme
- [x] JS HINT Validation - add to Readme
- [x] PYLINT Validation - - add to Readme

- [ ] All templates
- [x] account/login.html
- [x] account/logout.html
- [x] account/signup.html
- [x] admin/base_site.html
- [x] partials/hero-search
- [x] partials/onscreen_messages
- [x] Check base.html
- [x] all_vans
- [x] contact
- [x] dashboard
- [x] delete_booking
- [x] edit_booking
- [x] index
- [x] leave_feedback
- [x] services
- [x] van_detail
- [x] van_filter

App
- [x] admin
- [x] apps
- [x] forms.py
- [x] urls.py
- [x] models.py
- [x] views.py
- [x] choices.py
- [x] context_processors

Project
- [x] settings
- [x] urls

Static
- [x] style.css
- [x] admin.css
- [x] main.js

Tests
- [x] tests.py

Story Points = 2

**Comment by rstan-dev** [comment]
CSS - passed, 1 warning -  Same color for background-color and border-color - overriding bootstrap pagination

**Comment by rstan-dev** [comment]
Used https://pep8ci.herokuapp.com/ for Python Linter
https://jigsaw.w3.org/css-validator/
https://validator.w3.org/nu/
https://jshint.com/

**Comment by rstan-dev** [comment]
Default meta description added to base - dynamic meta description needed for each page - added to future dev

**Comment by rstan-dev** [comment]
Lighthouse performance under 50% - due to image width and height attributes and serving a bigger image size than is needed for responsive sizes - TBC

**Comment by rstan-dev** [comment]
updated pylint and lighthouse tests in readme
