### ISSUE TITLE
USERSTORY(# 28):  Final deployment

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#41]
As a developer I will ensure the final project is fully deployed to Heroku so that it matches the development project

EPIC #12 

Acceptance criteria
1. Given I am a developer the final project should be deployed correctly to a cloud hosting platform such as Heroku
2. Given I am a user the final website should function correctly, as the development version

Tasks

- [x] Check all links are working as expected
- [x] update requirements - pip3 freeze --local > requirements.txt
- [x] Run user story tests in production environment
- [x] Test for 404 manually
- [x] Test email sending and received

Story Points = 2

**Comment by rstan-dev** [comment]
Ensure email config settings are updated in settings

# Email Config
# Setting for development tests (remove for production)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Setting for production (enable for deployment)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_HOST_USER = 'yoomoov@outlook.com'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_PORT = 587
EMAIL_USE_TLS = True

**Comment by rstan-dev** [comment]
Error 404 tested using: https://yoomoov-2cbb8d75e399.herokuapp.com/edit_booking/640 (there is no booking 640 - results in a redirect to dashboard and Error 404 message - this works as expected

**Comment by rstan-dev** [comment]
All emails tested and received for user, admin and booking form email
