### ISSUE TITLE
USERSTORY(#29):  Final Checks

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/pp4-yoomoov#42]
As a developer, I will complete the final checks to ensure all criteria for the project have been met before submission

EPIC #13 

Acceptance criteria
1. All items on the project board should be completed or moved to a future iteration
2. All code should be checked to conform to standards
3. All testing should be completed, and final manual checks conducted on the deployed project

Tasks
- [x] Map all user stories to project
- [x] Update Readme with any stories that are incomplete
- [x] ensure all files are named correctly
- [x] Ensure all code has the required doc strings
- [x] Check for any commented out code and remove
- [x] Ensure all Problems Tab items in VS code are resolved and addressed in Readme
- [x] Ensure debug is set to false
- [x] Ensure there are no security keys visible
- [x] Ensure full deployment process has been documented in Readme
- [x] Ensure security features are explained and considered
- [x] Ensure Bugs found are documented as fixed or left
- [x] Ensure data schema is fully explained in the readme
- [x] Make sure GitHub repo and Project is set to public

Story Points = 2
